version: '3.7'

networks:
  pikcha-net_dev:
   driver: bridge

services:   
  mysql_image_dev:
    container_name: mysql_c_dev
    image: mysql/mysql-server:8.0.17
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    ports:
      - 3306:3306
    restart: always
    volumes:
      - dbvol_dev:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
      - pikcha-net_dev
    environment:
      MYSQL_ROOT_PASSWORD: HkQuvuw2s3UXKd      
      MYSQL_USER: pikcha_dbuser
      MYSQL_PASSWORD: xKnrHCWQ8PPKq
      MYSQL_DATABASE: pikcha_db

  adminer_dev:
    image: adminer
    container_name: myadmin_c_dev
    restart: always
    ports:
      - 8080:8080
    networks:
      - pikcha-net_dev

volumes:
  dbvol_dev:

