version: '3.7'

networks:
  pikcha-net:
   driver: bridge

services:
  webapp:
    container_name: web_c
    image: pikchaweb:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      DB_CONNECTION_STRING: server=mysql_image;port=3306;database=pikcha_db;uid=root;pwd=MySecret;
    depends_on:
      - mysql_image
    networks:
      - pikcha-net
   
  mysql_image:
    container_name: mysql_c
    image: mysql/mysql-server:8.0.17
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    ports:
      - 3306:3306
    restart: always
    volumes:
      - dbvol:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
      - pikcha-net
    environment:
      MYSQL_ROOT_PASSWORD: HkQuvuw2s3UXKd      
      MYSQL_USER: pikcha_dbuser
      MYSQL_PASSWORD: xKnrHCWQ8PPKq
      MYSQL_DATABASE: pikcha_db

  adminer:
    image: adminer
    container_name: myadmin_c
    restart: always
    ports:
      - 8080:8080
    networks:
      - pikcha-net

volumes:
  dbvol:

