version: "3.7"

networks:
  pikcha-net:
    driver: bridge

services:
  mssql_image:
    container_name: msdb_c
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    ports:
      - 1433:1433
    volumes:
      - dbvol:/var/lib/mssql
    networks:
      - pikcha-net
    environment:
      SA_PASSWORD: "My_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

volumes:
  dbvol:
