stages:
  - build-test

build-test-job:
 stage: build-test
 networks:
  pikcha-net:
   driver: bridge
 services:
  webapp:
    container_name: web_c
    image: pikchaweb:latest
    build:
      context: .
      dockerfile: ./PikchaWebApp/Dockerfile
    ports:
      - 8000:80
    environment:
      DB_CONNECTION_STRING: Server=mssql_image;Database=master;User Id=sa;Password=My_password123;
    depends_on:
      - mssql_image
    networks:
      - pikcha-net
      
  mssql_image:
    container_name: msdb_c
    image: "mcr.microsoft.com/mssql/server" 
    restart: always
    volumes:
      - dbvol:/var/lib/mssql
    networks:
      - pikcha-net
    environment:
            SA_PASSWORD: "My_password123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

 volumes:
  dbvol:
 only:
    - backend


