// Auth Types
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

// Account Types
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATED = "USER_UPDATED";
export const LOGGED_OUT = "LOGGED_OUT";
export const USER_ERROR = "USER_ERROR";
export const SIGNATURE_LOADING = "SIGNATURE_LOADING";
export const SIGNATURE_LOADED = "SIGNATURE_LOADED";
export const ARTIST_FOLLOWED = "ARTIST_FOLLOWED";
export const ARTIST_UNFOLLOWED = "ARTIST_UNFOLLOWED";

// Alert Types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Dropdown Types
export const CREATE_PROFILE_DROPDOWN = "CREATE_PROFILE_DROPDOWN";
export const REMOVE_PROFILE_DROPDOWN = "REMOVE_PROFILE_DROPDOWN";
export const CREATE_CART_DROPDOWN = "CREATE_CART_DROPDOWN";
export const REMOVE_CART_DROPDOWN = "REMOVE_CART_DROPDOWN";

// Gallery Types
export const PHOTOS_LOADED = "PHOTOS_LOADED";
export const PHOTOS_LOADING = "PHOTOS_LOADING";
export const PHOTOS_ERROR = "PHOTOS_ERROR";
export const PHOTO_SELECTED = "PHOTO_SELECTED";
export const PHOTO_DESELECTED = "PHOTO_DESELECTED";

// Pikcha100 && Artist100
export const PIKCHA100_LOADED = "PIKCHA100_LOADED";
export const ARTIST100_LOADED = "ARTIST100_LOADED";
export const PIKCHA100_LOADING = "PIKCHA100_LOADING";
export const ARTIST100_LOADING = "ARTIST100_LOADING";
export const TOP100_ERROR = "TOP100_ERROR";

// Product Types
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SET_SIZE = "SET_SIZE";
export const SET_MATERIAL = "SET_MATERIAL";
export const SET_FRAME = "SET_FRAME";
export const SET_BORDER = "SET_BORDER";
export const SET_FINISH = "SET_FINISH";
export const CLEAR_CUSTOMISATIONS = "CLEAR_CUSTOMISATIONS";

// Artist Types
export const ARTIST_LOADED = "ARTIST_LOADED";
export const ARTIST_LOADING = "ARTIST_LOADING";
export const ARTIST_ERROR = "ARTIST_ERROR";

// Cart Types
export const PRODUCT_ADDED = "PRODUCT_ADDED";
export const PRODUCT_REMOVED = "PRODUCT_REMOVED";
export const CLEAR_CART = "CLEAR_CART";

// Modal Types
export const CREATE_MODAL = "CREATE_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";
