// Auth Types
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

// Account Types
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATED = "USER_UPDATED";
export const LOGGED_OUT = "LOGGED_OUT";
export const USER_ERROR = "USER_ERROR";
export const SIGNATURE_LOADING = "SIGNATURE_LOADING";
export const SIGNATURE_LOADED = "SIGNATURE_LOADED";
export const ARTIST_FOLLOWED = "ARTIST_FOLLOWED";
export const ARTIST_UNFOLLOWED = "ARTIST_UNFOLLOWED";

// Alert Types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Nav Types
export const DROPDOWN_OPEN = "DROPDOWN_OPEN";
export const DROPDOWN_CLOSED = "DROPDOWN_CLOSED";

// Gallery Types
export const GALLERY_LOADED = "GALLERY_LOADED";
export const GALLERY_LOADING = "GALLERY_LOADING";
export const GALLERY_ERROR = "GALLERY_ERROR";
export const GALLERY_RESET = "GALLERY_RESET";

// Pikcha100 Types
export const PIKCHA100_LOADED = "PIKCHA100_LOADED";
export const PIKCHA100_LOADING = "PIKCHA100_LOADING";
export const PIKCHA100_ERROR = "PIKCHA100_ERROR";
export const PIKCHA100_RESET = "PIKCHA100_RESET";

// Artist100 Types
export const ARTIST100_LOADED = "ARTIST100_LOADED";
export const ARTIST100_LOADING = "ARTIST100_LOADING";
export const ARTIST100_ERROR = "ARTIST100_ERROR";
export const ARTIST100_RESET = "ARTIST100_RESET";

// Product Types
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SET_SIZE = "SET_SIZE";
export const SET_MATERIAL = "SET_MATERIAL";
export const SET_FRAME = "SET_FRAME";
export const SET_BORDER = "SET_BORDER";
export const SET_FINISH = "SET_FINISH";
export const CLEAR_CUSTOMISATIONS = "CLEAR_CUSTOMISATIONS";

// Profile Types
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const PROFILE_RESET = "PROFILE_RESET";
export const ARTIST_PHOTOS_LOADED = "ARTIST_PHOTOS_LOADED";
export const ARTIST_PHOTOS_LOADING = "ARTIST_PHOTOS_LOADING";
export const ARTIST_PHOTOS_ERROR = "ARTIST_PHOTOS_ERROR";
export const ARTIST_PHOTOS_RESET = "ARTIST_PHOTOS_RESET";

// Cart Types
export const PRODUCT_ADDED = "PRODUCT_ADDED";
export const PRODUCT_REMOVED = "PRODUCT_REMOVED";
export const CLEAR_CART = "CLEAR_CART";

// Modal Types
export const MODAL_CREATED = "MODAL_CREATED";
export const MODAL_REMOVED = "MODAL_REMOVED";
